version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  flaskapp:
    depends_on:
      - dynamodb
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: practice
      FLASK_ENV: development
      FLASK_DEBUG: '0'
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    build:
      context: ./
      dockerfile: Dockerfile