version: '3.8'

services:
  flaskapp:
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: practice
      FLASK_ENV: development
      FLASK_DEBUG: '0'
    build:
      context: ./
      dockerfile: Dockerfile